Added new flags introduced in IIS 10 version 1809.
MicrosoftDocs/iis-docs pull request #1054
Opened 2024-06-06 18:49 UTC by lextm

IIS 10 version 1809 introduced new `sslFlags` values but no doc was made available for them, https://learn.microsoft.com/en-us/iis/get-started/whats-new-in-iis-10-version-1809/new-features-introduced-in-iis-10-1809#new-binding-flags

2024-06-06 18:52 UTC, Rick-Anderson commented
@tdykstra  what would it take to get a preview build here?

2024-06-06 19:03 UTC, Rick-Anderson commented
@lextm  please review [Configuration](https://review.learn.microsoft.com/en-us/aspnet/core/data/entity-framework-6?view=aspnetcore-8.0&branch=pr-en-us-32762#configuration) build. It looks good to me.

2024-06-06 19:16 UTC, Rick-Anderson requested changes

2024-06-06 19:16 UTC, Rick-Anderson commented on iis/configuration/system.applicationHost/sites/siteDefaults/bindings/binding.md
> +| `sslFlags` | Optional uint attribute but works like flags type, with the following possible flags. <table> <tbody> <tr> <th>Value</th> <th>Description</th></tr> <tr> <th><code>0</code></th> <td>The
```suggestion
| `sslFlags` | Optional `uint` attribute that works like flags type, with the following possible flags: <table> <tbody> <tr> <th>Value</th> <th>Description</th></tr> <tr> <th><code>0</code></th> <td>The secure connection made using an IP/Port combination. Only one certificate can be bound to a combination of IP address and the port.</td></tr> <tr> <th><code>1</code></th> <td>The secure connection made using the port number and the host name obtained by using Server Name Indication (SNI).</td></tr> <tr> <th><code>2</code></th> <td>The secure connection be made using the centralized SSL certificate store.</td></tr> <tr> <th><code>4</code></th> <td>Disable HTTP/2.</td></tr> <tr> <th><code>8</code></th> <td>Disable OCSP Stapling.</td></tr> <tr> <th><code>16</code></th> <td>Disable QUIC.</td></tr> <tr> <th><code>32</code></th> <td>Disable TLS 1.3 over TCP.</td></tr> <tr> <th><code>64</code></th> <td>Disable Legacy TLS.</td></tr> </tbody></table> Centralized SSL certificate support enables creating a centralized certificate store that can contain multiple certificate files. The certificate files can be named to correspond to the host names that they contain. This enables creating a binding that only requires a port, rather than an IP/port or a host name/port combination. When a request comes in, IIS matches the port, determines the host name from the request, and searches the centralized certificate store for a certificate file with a matching name. It uses that certificate. <br><br> With a Server Name Indicator (SNI), the host name is exchanged as part of the SSL handshake. SNI is enabled in the **Add Site Binding** dialog box when adding a binding with a type of HTTPS. This is useful for SSL connections that host multiple servers on a single network address. <br><br> Values greater than 4 are only supported in IIS 10 version 1809 and higher. The default value is `0`. |
```

2024-06-06 20:58 UTC, tdykstra commented
> @tdykstra what would it take to get a preview build here?

I don't know -- ask Alma?

2024-06-06 21:19 UTC, Rick-Anderson approved these changes

2024-06-11 03:59 UTC, merged

2024-06-11 04:00 UTC, Rick-Anderson commented
@lextm  can you check the live to see if your changes render as you expected?