SFI images IIS-docs sev1-2 updates only
MicrosoftDocs/iis-docs pull request #1072
Opened 2024-10-28 01:29 UTC by wadepickett

2024-10-28 16:29 UTC, tdykstra approved these changes
It seems extreme to blank out localhost IP addresses, but if that's what we're directed to do, this PR LGTM

2024-10-28 16:53 UTC, Rick-Anderson commented
> It seems extreme to blank out localhost IP addresses, but if that's what we're directed to do, this PR LGTM

I'd like to pushback and get some reason why. There's many tools and operations that rely on the loopback IP

2024-10-28 16:57 UTC, Rick-Anderson requested changes

2024-10-28 16:57 UTC, Rick-Anderson commented on iis/configuration/configurationRedirection/_static/image11.png
What does the doc look without these? Why can't you issue a warning although I don't know what warning that would be. This is a tool that requires PW.

2024-10-28 16:57 UTC, Rick-Anderson commented on iis/configuration/system.applicationHost/sites/site/ftpServer/index/_static/image13.png
provide the link to this doc

2024-10-28 16:57 UTC, Rick-Anderson commented on iis/configuration/system.applicationHost/sites/site/ftpServer/security/authentication/anonymousAuthentication/_static/image13.png
ditto for all these deleted images.

2024-10-28 17:30 UTC, Rick-Anderson commented
@wadepickett  can you cite a reference to removing loop back IP?

2024-10-28 17:30 UTC, wadepickett commented
Thanks for the suggestions and info:

We were instructed to remove what was called out, as a top priority, and IP's were specifically called out in those cases,  so that is what I was doing. To me, any example simply used as an fictional example, which would be 99% of all of the doc issues, would be an odd high bar to hit , but they were intentionally flagging fictional examples from what I could see.  Almost all the flags are for fictional examples for all doc repos.

@Rick, do you have a link to an example you like where the images are not addressed as requested, but instead they use an informational message instead at the top of the doc that you are referring to on Azure?

Who do we push back to?  The SFI engineers?

The images were updated, not deleted and gone.  For binaries, they are replaced when you update and there is no way around that.  It is confusing when you refer to images as just "deleted" when they have been updated.  It would be helpful if you communicate which you are referring to.

2024-10-28 17:42 UTC, wadepickett commented on iis/configuration/system.applicationHost/sites/site/ftpServer/index/_static/image13.png
https://github.com/MicrosoftDocs/iis-docs/blob/main/iis/configuration/system.applicationHost/sites/site/ftpServer/index.md

https://review.learn.microsoft.com/en-us/iis/configuration/system.applicationhost/sites/site/ftpserver/security/?branch=pr-en-us-1072

2024-10-28 17:42 UTC, Rick-Anderson commented
> We were instructed to remove what was called out, 

Where were we instructed to blindly remove everything flagged? AFAIK, we were instructed to review everything flagged. Unless you can prove the loop back IP is a risk, it should be reviewed and exempted.

> Almost all the flags are for fictional examples for all doc repos.

Loop back is not fictional, it's an IP needed to for loop-back.

You can replace fictional IP's with an IP from the list of approved IP's, just as with GUIDs

2024-10-28 17:50 UTC, wadepickett commented on iis/configuration/system.applicationHost/sites/site/ftpServer/security/authentication/anonymousAuthentication/_static/image13.png
https://review.learn.microsoft.com/en-us/IIS/configuration/system.applicationhost/sites/site/ftpserver/security/authentication/anonymousauthentication?branch=pr-en-us-1072

2024-10-28 17:52 UTC, Rick-Anderson commented
@wadepickett 
See https://github.com/MicrosoftDocs/reusable-content/pull/213/files
ROPC is significantly higher risk that IP's

> @rick, do you have a link to an example

I don't think `Rick Bradley` cares

> they were intentionally flagging fictional examples from what I could see.

Loop-back is not fictional

2024-10-28 17:56 UTC, Rick-Anderson commented
The first one is fine but I question why you need to make any changes. The PW is obscured. Admin is used through out the docs.

You 've left an obscured PW here, which is fine because it's obscured.

![image](https://github.com/user-attachments/assets/52b8646c-b0e0-4353-885b-46d1cf2fb559)

2024-10-28 18:00 UTC, Rick-Anderson commented
You've left in the text, which can be copy/pasted. You can't do that easily with an image. It's inconsistent.

Specify FTP IP filtering options that allow access from 
# 127.0.0.1 
 and deny access from the 
# 169.254.0.0/255.255.0.0 
range of IP addresses.


```
<location path="ftp.example.com">
  <system.ftpServer>
    <security>
      <authorization>
        <add accessType="Allow" roles="administrators" permissions="Read, Write" />
      </authorization>
      <requestFiltering>
        <fileExtensions allowUnlisted="true">
          <add fileExtension=".exe" allowed="false" />
          <add fileExtension=".bat" allowed="false" />
          <add fileExtension=".cmd" allowed="false" />
        </fileExtensions>
        <requestLimits maxAllowedContentLength="1000000" maxUrl="1024" />
        <hiddenSegments>
          <add segment="_vti_bin" />
        </hiddenSegments>
      </requestFiltering>
      <ipSecurity enableReverseDns="false" allowUnlisted="true">
        <add ipAddress="127.0.0.1" allowed="true" />
        <add ipAddress="169.254.0.0" subnetMask="255.255.0.0" allowed="false" />
```

2024-10-28 18:35 UTC, wadepickett commented
> The first one is fine but I question why you need to make any changes. The PW is obscured. Admin is used through out the docs.

I was trying to make the best of the whole awkward situation in each case.  The way the dialog was introduced, it felt like the dialog fields could be in a state of not filled out yet.  I was asked to remove the first few entered fields, user name etc, and it seemed out of state to leave in the obsured passwords at the bottom.

![image](https://github.com/user-attachments/assets/e4df2680-4fda-4046-a420-678049cbcb87)

I can redo to leave the dialog half filled, with obscured passwords in there.  Is that what you want?

Since the loopback IP needs to stay there in every case, for which I will revert.   It might be faster to call out the ones you feel actually need to be removed.

As far as some message at the top of the doc, as you say, what would that be?  I can't think of one that is appropriate either.  If these are flags that simply should not be flagged I can not that, adjust the PR and update the spreadsheet.

2024-10-28 18:44 UTC, Rick-Anderson commented
> We were asked to address the first few entered fields, user name

Asked by whom?
the user name Administrator is used throughout the docs. The security is in the PW, not in security by obscurity on the user name.

2024-10-28 18:47 UTC, wadepickett commented
Maybe we can break this down into some guidelines I can follow here.  I am not that familier with the IIS repo.

1. Leave in the loopback address, typically 127.0.0.1.
2. Leave in Administrator.
3. Whe details like a local path is left in keep those.
4. Leave in completely obscured passwords, (replaced with dots) even though they are called out.


any other guidelines you see here from the image list I could add before redoing?

2024-10-28 18:51 UTC, Rick-Anderson commented
I don't care that 
![image](https://github.com/user-attachments/assets/d09ad8fb-1f44-457a-ae1b-338b49d8193c)

was changed, I just question the need to change it.
The loop back shouldn't be changed

2024-10-28 18:54 UTC, Rick-Anderson commented
[This walkthrough contains a series of steps in which you log in to your FTP site using an IIS Manager account. These steps should only be followed on the server itself using the loopback address or over SSL from a remote server.](https://learn.microsoft.com/en-us/iis/publish/using-the-ftp-service/configure-ftp-with-iis-manager-authentication-in-iis-7)

2024-10-28 21:10 UTC, wadepickett commented
@Rick-Anderson @tdykstra :

Maybe we can break this down into some guidelines I can follow here. I am not that familier with the IIS repo.

- Leave in the loopback address, typically 127.0.0.1.
- Leave in Administrator when it is used as the user name.
- When details like a local path is left in, keep those.
- Leave in completely obscured passwords, (replaced with dots) even though they are called out.

Any other guidelines you see here from the image list I could add before redoing?

2024-10-28 21:19 UTC, wadepickett commented
> they were intentionally flagging fictional examples from what I could see.

My point being that the bar for what they would allow seemed very high, not that the specific issue of a loopback address is fictional, nor that an IP is the same as a GUID.

2024-10-28 21:49 UTC, tdykstra commented
> Any other guidelines you see here from the image list I could add before redoing?

* Leave in the name of a local database used for the article, like "School" or "Blogging" or "AdventureWorks."
* Leave in localdb or SQLExpress used as server name. Consider leaving in localdb connection strings.

2024-10-28 21:51 UTC, wadepickett commented
> > Any other guidelines you see here from the image list I could add before redoing?
> 
> * Leave in the name of a local database used for the article, like "School" or "Blogging" or "AdventureWorks."
> * Leave in localdb or SQLExpress used as server name. Consider leaving in localdb connection strings.

Thanks!  That helps me get a better idea of where the line is compared to what is getting flagged.  Much appreciated!

2024-10-28 22:07 UTC, Rick-Anderson commented
> My point being that the bar for what they would allow seemed very high

Where, that's not what I read.

2024-10-28 22:15 UTC, wadepickett commented
> > My point being that the bar for what they would allow seemed very high
> 
> Where, that's not what I read.

the bar for what they would allow seemed very high given what they were flagging.

2024-10-28 22:34 UTC, fatmasamuk commented
Don't  sen me mesage

29 Eki 2024 Sal 01:15 tarihinde Wade Pickett ***@***.***>
şunu yazdı:

> My point being that the bar for what they would allow seemed very high
>
> Where, that's not what I read.
>
> the bar for what they would allow seemed very high given what they were
> flagging.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MicrosoftDocs/iis-docs/pull/1072#issuecomment-2442775786>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQCRRD3INKLPEID6XDFD4HLZ52ZRVAVCNFSM6AAAAABQWMAMJOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINBSG43TKNZYGY>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-10-28 22:55 UTC, Rick-Anderson commented
> the bar for what they would allow seemed very high given what they were flagging.

You don't understand flagging. Flagging means take a look, it's not a directive to delete content.

The bar is very low for flagging.

2024-11-03 23:11 UTC, wadepickett commented on iis/install/installing-publishing-technologies/installing-and-configuring-web-deploy/_static/image9.png
Live doc for this image for reference:
https://learn.microsoft.com/en-us/iis/install/installing-publishing-technologies/installing-and-configuring-web-deploy

Details flagged are not used specifically for the tutorial and the state of the image can represent a user not selected yet as opposed to one selected given the tutorial context where it is used.

2024-11-03 23:13 UTC, wadepickett commented on iis/publish/using-the-ftp-service/configuring-ftp-firewall-settings-in-iis-7/_static/image25.png
The Data Channel Port range is a ficticious range specific to the tutorial and needs to show it in a greyed out state, so left it in.  However the External IP address does not need to be in the dialog yet at this point and an example is already provided in the dialog below the field in case there is any confustion about what would go in there so removed that item that was flagged.

2024-11-03 23:15 UTC, wadepickett commented on iis/get-started/whats-new-in-iis-8/iis-80-server-name-indication-sni-ssl-scalability/_static/image27.png
I used grey out instead of matching black to make it clear there is information that would be there but has been blanked out.

2024-11-04 17:30 UTC, wadepickett commented on iis/get-started/whats-new-in-iis-10/http2-on-iis/_static/image4.png
Inline image comments [Preview in doc](https://review.learn.microsoft.com/en-us/IIS/get-started/whats-new-in-iis-10/http2-on-iis?branch=pr-en-us-1072)

2024-11-04 20:12 UTC, tdykstra approved these changes

2024-11-04 23:58 UTC, Rick-Anderson approved these changes

2024-11-05 00:00 UTC, merged