Update paragraph "using server variables in rewrite rules"
MicrosoftDocs/iis-docs pull request #220
Opened 2018-10-15 11:58 UTC by Cezus

What is described in paragraph "using server variables in rewrite rules" is not correct. The information In the list about http headers is not correct. A dash in the http header is not converted to an underscore. It should be stated that de underscore from the condition input is converted to a dash. When the statement from the text was true, I could handle a HTTP header with an underscore in it.

2018-10-15 12:08 UTC, Cezus commented
I just found the page where it is correctly stated: https://docs.microsoft.com/en-us/iis/extensions/url-rewrite-module/url-rewrite-module-20-configuration-reference#accessing-response-headers-from-rewrite-rules

"All underscore ("_") symbols in the name are converted to dash symbols ("-")."

2018-10-15 13:01 UTC, lextm commented
@Cezus You are wrong. This paragraph is talking about incoming requests, while the one you linked is about "responses".

2018-10-15 13:37 UTC, Cezus commented
> @Cezus You are wrong. This paragraph is talking about incoming requests, while the one you linked is about "responses".

You are right, that article does not apply in this matter. But the problem I try to address is still valid. The problem is as following: https://stackoverflow.com/questions/52816655/how-can-url-rewrite-match-http-headers-with-underscores

2022-01-25 23:53 UTC, Rick-Anderson commented
@John-Hart please review

2022-01-26 00:07 UTC, John-Hart commented
@ning51 could you please verify this?

2022-10-28 18:30 UTC, ning51 requested changes
This paragraph talks about naming convention of server variables, and it is correct. You may consider add the proposed content at the end of the section "Using server variables in rewrite rules" with an example.

2023-03-09 23:19 UTC, Rick-Anderson commented
@ning51 @John-Hart if this is an improvement, can I S&M. @ning51  can create an issue to track the suggestion.

2025-04-01 21:05 UTC, closed without merging