Update live
MicrosoftDocs/iis-docs pull request #529
Opened 2020-11-10 17:41 UTC by shirhatti

2020-11-10 17:50 UTC, Rick-Anderson commented on iis/install/web-platform-installer/web-platform-installer-direct-downloads.md
> + In some cases, it may be helpful to be able to download the Web Platform Installer directly vs using the launcher to get started. Below are the links for the current version (WebPI 5.1).
```suggestion
 In some cases, it may be helpful to be able to download the Web Platform Installer directly rather than using the launcher to get started. The following links are for the current version (WebPI 5.1).  
```

2020-11-10 17:52 UTC, Rick-Anderson requested changes

2020-11-10 17:52 UTC, Rick-Anderson commented on iis/install/web-platform-installer/web-platform-installer-direct-downloads.md
> + x86: [WebPI 5.1 x86 MSI] (https://go.microsoft.com/fwlink/?LinkId=287165)
```suggestion
 x86: [WebPI 5.1 x86 MSI](https://go.microsoft.com/fwlink/?LinkId=287165)
```

2020-11-10 17:52 UTC, Rick-Anderson commented on iis/install/web-platform-installer/web-platform-installer-direct-downloads.md
> + x64: [WebPI 5.1 x64 MSI] (https://go.microsoft.com/fwlink/?LinkId=287166)
```suggestion
 x64: [WebPI 5.1 x64 MSI](https://go.microsoft.com/fwlink/?LinkId=287166)
```

2020-12-03 01:44 UTC, shirhatti commented
@Rick-Anderson Good to merge?

2020-12-03 01:46 UTC, Rick-Anderson approved these changes

2020-12-03 02:45 UTC, merged