Update running-iis-express-from-the-command-line.md
MicrosoftDocs/iis-docs pull request #591
Opened 2021-11-08 01:58 UTC by Trace-Elements0

Adding a note for powershell users who may attempt to use powershell's ability to run cmd commands

2022-03-09 23:48 UTC, Rick-Anderson commented on iis/extensions/using-iis-express/running-iis-express-from-the-command-line.md
> +     > If you're using PowerShell, `iisexpress /?` will not work. To instruct PowerShell to run the command in the current directory you must prefix the command with `.\`. So the first command in ste
In PowerShell, the first command is `.\iisexpress /?`

2022-03-09 23:51 UTC, Rick-Anderson requested changes

2022-03-09 23:51 UTC, Rick-Anderson commented on iis/extensions/using-iis-express/running-iis-express-from-the-command-line.md
> +     > If you're using PowerShell, `iisexpress /?` will not work. To instruct PowerShell to run the command in the current directory you must prefix the command with `.\`. So the first command in ste
@Trace-Elements0  you've disabled writing to your branch. Can you replace your note with my version?

2022-03-15 20:17 UTC, Rick-Anderson commented
@Trace-Elements0  can you resubmit this PR and not block commits?

2022-03-15 20:17 UTC, closed without merging

2022-03-19 22:34 UTC, Trace-Elements0 commented
Will do. Not sure how I blocked commits, sorry about that.

2022-03-21 21:28 UTC, Rick-Anderson commented
> Will do. Not sure how I blocked commits, sorry about that.

There is a check box you must of accidently unchecked. No problem.