Wb fix missing alttext mmd
MicrosoftDocs/iis-docs pull request #638
Opened 2022-03-10 19:05 UTC by MeeraDi

2022-03-10 21:03 UTC, MeeraDi commented
Hi, @Rick-Anderson, @mcleblanc, @v-andreaco
This PR is ready for final review.

2022-03-10 23:58 UTC, Rick-Anderson requested changes

2022-03-10 23:58 UTC, Rick-Anderson commented on iis/extensions/configuring-application-request-routing-arr/achieving-high-availability-and-scalability-arr-and-nlb.md
>      [![](achieving-high-availability-and-scalability-arr-and-nlb/_static/image37.jpg)](achieving-high-availability-and-scalability-arr-and-nlb/_static/image36.jpg)
missing, please review the build report

2022-03-10 23:58 UTC, Rick-Anderson commented on iis/extensions/configuring-application-request-routing-arr/achieving-high-availability-and-scalability-arr-and-nlb.md
>      [![](achieving-high-availability-and-scalability-arr-and-nlb/_static/image37.jpg)](achieving-high-availability-and-scalability-arr-and-nlb/_static/image36.jpg)
For this file
<img width="237" alt="image" src="https://user-images.githubusercontent.com/3605364/157775391-fcfb1244-d858-49f6-93a7-9c6f8c30d257.png">

2022-03-10 23:58 UTC, Rick-Anderson commented on iis/develop/windows-web-application-gallery/introducing-the-windows-web-application-gallery.md
>  The Web Application Gallery also provides a way for developers to reach millions of Windows users. When an application is accepted by the Web Application Gallery, the application is added to the Web
For this file, from the build report
Line 4: [Suggestion-[PR only](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/pr-only?branch=main)] Attribute 'description' with value 'The Windows Web Application Gallery makes it easy to explore, discover and install popular community ASP.Net and PHP applications on Windows. Users can brows...' is duplicated in 'develop/windows-web-application-gallery/introducing-the-windows-web-application-gallery.md(4,14)', 'develop/windows-web-application-gallery/windows-web-application-gallery-principles.md(4,14)'.

2022-03-11 16:13 UTC, MeeraDi commented on iis/extensions/configuring-application-request-routing-arr/achieving-high-availability-and-scalability-arr-and-nlb.md
>      [![](achieving-high-availability-and-scalability-arr-and-nlb/_static/image37.jpg)](achieving-high-availability-and-scalability-arr-and-nlb/_static/image36.jpg)
@Rick-Anderson the rest of this file will be addressed in another PR.

2022-03-11 16:16 UTC, MeeraDi commented
@Rick-Anderson 
cc: @v-andreaco 
I updated the description metadata. The other missing alttext will be fixed in another PR.

2022-03-11 19:17 UTC, Rick-Anderson approved these changes

2022-03-11 19:18 UTC, merged