Alttext5
MicrosoftDocs/iis-docs pull request #672
Opened 2022-03-16 17:51 UTC by v-emilypr

2022-03-16 18:33 UTC, v-emilypr commented
@Rick-Anderson, @mcleblanc
This PR addresses missing alt text and is ready for final review.

2022-03-16 19:28 UTC, Rick-Anderson commented
@v-emilypr  can you check the build report?
https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C16%5C90f071cf-c002-b629-5e11-5bc968bb67ca%5CPullRequest%5C202203161841516918-672%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-16T18%3A46%3A44Z&sr=b&sp=r&sig=3VkF46sStnWEUjFA5h52sTX6WmMIL8H%2Ba4NlqOozDuw%3D

<img width="497" alt="image" src="https://user-images.githubusercontent.com/3605364/158674353-502f4f00-b196-42f6-ae89-9846f909a54d.png">

2022-03-16 19:29 UTC, Rick-Anderson requested changes
Please fix build warnings.

2022-03-16 19:29 UTC, Rick-Anderson commented on iis/application-frameworks/running-classic-asp-applications-on-iis-7-and-iis-8/using-failed-request-tracing-to-troubleshoot-classic-asp-errors.md
> +![Screenshot of a browser window displaying the Request Summary of a failed trace log.](using-failed-request-tracing-to-troubleshoot-classic-asp-errors/_static/image1.jpg)
Line 106: [Warning-[PR only](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/pr-only?branch=main)] Alt text 'Screenshot of a browser window displaying the Request Summary of a failed trace log.' is duplicated. Within an article, alt text must be unique.

2022-03-16 19:29 UTC, Rick-Anderson commented on iis/application-frameworks/running-classic-asp-applications-on-iis-7-and-iis-8/using-failed-request-tracing-to-troubleshoot-classic-asp-errors.md
> +![Screenshot of a browser window displaying the Request Summary of a failed trace log.](using-failed-request-tracing-to-troubleshoot-classic-asp-errors/_static/image5.jpg)
Line 158: [Warning-[PR only](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/pr-only?branch=main)] Alt text 'Screenshot of a browser window displaying the Request Summary of a failed trace log.' is duplicated. Within an article, alt text must be unique.

2022-03-21 16:41 UTC, v-emilypr commented
@Rick-Anderson, @mcleblanc
The duplicated text has been corrected and is ready for final review. My apologies on the delay in resolving as I was out of the office. Thanks :)

2022-03-21 21:56 UTC, Rick-Anderson approved these changes

2022-03-21 21:56 UTC, merged