added alt text
MicrosoftDocs/iis-docs pull request #705
Opened 2022-03-22 00:17 UTC by v-emilypr

2022-03-22 14:20 UTC, MeeraDi commented on iis/publish/using-web-deploy/powershell-scripts-for-automating-web-deploy-setup.md
> +![Screenshot of Powershell console with results of scripting.](powershell-scripts-for-automating-web-deploy-setup/_static/image5.png)
Screenshot of a Powershell console with results of scripting. (to be consistent with others)

2022-03-22 14:21 UTC, MeeraDi commented on iis/publish/using-web-deploy/powershell-scripts-for-automating-web-deploy-setup.md
> +![Screenshot of a Powershell console with scripting to create database.](powershell-scripts-for-automating-web-deploy-setup/_static/image16.png)
"the" database or "a" database?

2022-03-22 23:19 UTC, Rick-Anderson approved these changes

2022-03-23 00:51 UTC, Rick-Anderson commented
@v-emilypr check the build report
Line 73: [Warning] Missing alternate text for image 'add/_static/image8.png'. Alt text is required for accessibility.

2022-03-23 01:19 UTC, Rick-Anderson requested changes
Fix missing atl from build report

2022-03-23 21:03 UTC, v-emilypr commented
@Rick-Anderson Line 73 added and ready for final review.

2022-03-24 00:08 UTC, Rick-Anderson approved these changes

2022-03-24 00:08 UTC, merged