[Bulk| Validations: Fix missing alt text issues 9
MicrosoftDocs/iis-docs pull request #762
Opened 2022-03-28 21:18 UTC by v-lkasturi

- Added alternate texts to all the screenshots.
- Convert absolute link to relative link.

2022-03-28 22:08 UTC, RedZephyr13 commented on iis/configuration/system.webServer/fastCgi/application/environmentVariables/index.md
> +   [![Screenshot shows the EnvironmentVariables Collection Editor dialog box to add Members.](index/_static/image26.png)](index/_static/image25.png)
I think separating the individual words for "EnvironmentVariables" would make sense here.

2022-03-28 22:08 UTC, RedZephyr13 commented on iis/configuration/system.webServer/fastCgi/application/environmentVariables/index.md
> +   [![Screenshot shows the EnvironmentVariables Collection Editor dialog box highlighting the Name.](index/_static/image28.png)](index/_static/image27.png)
I think separating the individual words for "EnvironmentVariables" would make sense here.

2022-03-29 00:02 UTC, v-lkasturi commented
@Rick-Anderson @mcleblanc The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

CC: @MonicaRush @snoviking

2022-03-29 02:34 UTC, Rick-Anderson approved these changes

2022-03-29 02:36 UTC, Rick-Anderson requested changes
Can you fix the warnings in the build report.

2022-03-29 20:41 UTC, v-lkasturi commented
@Rick-Anderson @mcleblanc The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

CC: @MonicaRush @snoviking

2022-04-04 18:41 UTC, Rick-Anderson commented
@v-lkasturi @RedZephyr13 Can you fix the warnings in the build report.

2022-04-04 18:45 UTC, Rick-Anderson approved these changes

2022-04-04 18:45 UTC, merged