[BrokenLinksH2] Fixed broken links
MicrosoftDocs/iis-docs pull request #903
Opened 2022-06-11 18:53 UTC by kturetz

Fixed broken links in iis-docs.

2022-06-13 18:14 UTC, kturetz commented
**Global effort to fix broken links** 

@Rick-Anderson 
@rmcmurray 
@david-puglielli 

The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. I’d very much appreciate your timely review and feedback on the link changes I’ve suggested. Thanks!

2022-06-14 18:02 UTC, wadepickett requested changes
Great to see a lot of these fixed.  
Some of the links that were addressed in changes seem to be out of date and broken.  I noted each.  I also corrected a few minor typos.  I'll commit the ones that have no pending question about them.

2022-06-14 18:02 UTC, wadepickett commented on iis/application-frameworks/running-classic-asp-applications-on-iis-7-and-iis-8/classic-asp-parent-paths-are-disabled-by-default.md
> +> `https://support.microsoft.com/kb/332117`
This link appears to be broken.  I didn't see a replacement to suggest.  Not sure where that article went.  Searching on the site for the kb number suggests there is a file that includes that keyword but says the site is not allowed to show it.

2022-06-14 18:17 UTC, kturetz commented on iis/application-frameworks/install-and-configure-php-applications-on-iis/openads-on-iis.md
> +First, download the latest stable release of the OpenAds application. For this article, we use openads-2.4.1 downloaded from the mirror `http://www.openads.org/products/openads/download?ext=zip&amp;u
Thanks for your detective work, Wade! Too bad they didn't just forward the old domain!

2022-06-14 18:24 UTC, kturetz commented on iis/application-frameworks/install-and-configure-php-applications-on-iis/openads-on-iis.md
> +For more information about OpenAds, see `http://www.openads.org/`.
How about:

For more information about Revive Adserver (formerly OpenAds), see `https://www.revive-adserver.com/`.

2022-06-14 18:28 UTC, kturetz commented on iis/application-frameworks/install-and-configure-php-applications-on-iis/openads-on-iis.md
> +First, download the latest stable release of the OpenAds application. For this article, we use openads-2.4.1 downloaded from the mirror `http://www.openads.org/products/openads/download?ext=zip&amp;u
How about this?

For this article, we use Revive Adserver (formerly OpenAds). See https://www.revive-adserver.com/.

2022-06-14 18:31 UTC, kturetz commented on iis/application-frameworks/install-and-configure-php-applications-on-iis/openads-on-iis.md
> +1. To start the installer, open a Web browser and point it to the directory in which `http://localhost/openads`. This starts the installer automatically. If it does not start automatically, use `http
This is getting a little tricky. If permissible, I'd comment out the links and add a paragraph:

For more information about Revive Adserver (formerly OpenAds), see https://www.revive-adserver.com/.

2022-06-14 20:30 UTC, wadepickett approved these changes
Updated per feedback and approved.

2022-06-14 20:30 UTC, wadepickett commented on iis/application-frameworks/install-and-configure-php-applications-on-iis/openads-on-iis.md
> +First, download the latest stable release of the OpenAds application. For this article, we use openads-2.4.1 downloaded from the mirror `http://www.openads.org/products/openads/download?ext=zip&amp;u
```suggestion
First, download the latest stable release of the OpenAds application. For this article, we use Revive Adserver (formerly OpenAds). See [https://www.revive-adserver.com/](https://www.revive-adserver.com/).
```

2022-06-14 20:30 UTC, wadepickett commented on iis/application-frameworks/install-and-configure-php-applications-on-iis/openads-on-iis.md
> +1. To start the installer, open a Web browser and point it to the directory in which `http://localhost/openads`. This starts the installer automatically. If it does not start automatically, use `http
```suggestion
1. To start the installer, open a Web browser and point it to the directory in which `http://localhost/openads`. This starts the installer automatically. For more information about Revive Adserver (formerly OpenAds), see [https://www.revive-adserver.com/](https://www.revive-adserver.com/). 
```

2022-06-14 20:30 UTC, wadepickett commented on iis/application-frameworks/install-and-configure-php-on-iis/secure-your-sql-server-database.md
> +- Security Enhancements in Microsoft SQL Server 2008 presentation `https://download.microsoft.com/download/d/1/f/d1f05c2e-0741-442d-859e-9417b377fdfa/Security%20Enhancements%20in%20SQL%20Server%20200
```suggestion
```

2022-06-14 20:30 UTC, wadepickett commented on iis/application-frameworks/running-classic-asp-applications-on-iis-7-and-iis-8/classic-asp-parent-paths-are-disabled-by-default.md
> +> `https://support.microsoft.com/kb/332117`
```suggestion
```

2022-06-14 20:32 UTC, wadepickett commented on iis/application-frameworks/install-and-configure-php-on-iis/secure-your-sql-server-database.md
> +- Security Enhancements in Microsoft SQL Server 2008 presentation `https://download.microsoft.com/download/d/1/f/d1f05c2e-0741-442d-859e-9417b377fdfa/Security%20Enhancements%20in%20SQL%20Server%20200
Removed link.

2022-06-14 20:32 UTC, wadepickett commented on iis/application-frameworks/running-classic-asp-applications-on-iis-7-and-iis-8/classic-asp-parent-paths-are-disabled-by-default.md
> +> `https://support.microsoft.com/kb/332117`
Removed link.

2022-06-14 20:36 UTC, wadepickett commented on iis/application-frameworks/install-and-configure-php-on-iis/secure-your-sql-server-database.md
> +- SQL Server 2008 Deployment Guide for Web Hosting Environments `https://download.microsoft.com/download/d/1/f/d1f05c2e-0741-442d-859e-9417b377fdfa/The%20architectural%20view%20of%20SQL%20Server.zip`
```suggestion
```

2022-06-14 20:36 UTC, wadepickett commented on iis/application-frameworks/install-and-configure-php-on-iis/secure-your-sql-server-database.md
> +- SQL Server 2008 Deployment Guide for Web Hosting Environments `https://download.microsoft.com/download/d/1/f/d1f05c2e-0741-442d-859e-9417b377fdfa/The%20architectural%20view%20of%20SQL%20Server.zip`
No longer available.  Removing.

2022-06-14 20:49 UTC, kturetz commented
Great work, @wadepickett! Are you able to merge this PR?

2022-06-14 20:49 UTC, merged