Validation issues | 1 (BULK)
MicrosoftDocs/iis-docs pull request #923
Opened 2022-07-22 21:18 UTC by damabe

This is a bulk update.

This PR is to fix issues related to build validation messages.

If these changes are not appropriate, please let me know. I'm only trying to clean up validation issues in this repo. So I can easily close this PR or modify it in whatever way is best for the content.

2022-07-22 21:22 UTC, damabe commented
Global effort to fix build validation errors

@Rick-Anderson @mcleblanc 

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

2022-08-05 19:10 UTC, jmart1428 commented
@Rick-Anderson @mcleblanc Please let us know if you'd like to see any additional changes in this PR. If no changes are required, you are welcome to merge. Thank you for your feedback!

2022-08-17 20:51 UTC, wadepickett requested changes
Thanks @damabe!  We need here is to know who to assign these soshir/shirhatti (Sourabh Shirhatti) topics to in bulk as ms.author, since Sourabh Shirhatti moved on.

I don't think assigning them to @mairaw is correct.  She is not on the IIS team.  She has touched them in the past as a content developer when she was once in that role.

(I'm not assigned to these either, I could see however the PR's sitting here so I thought I would jump in to try to help resolve if I could.)  

On your PR #924 I asked John Hart if he know who these IIS topics belonging to soshir/shirattie (Sourabh Shirhatti) should be assigned to now.  Hopefully John might know who.

2022-08-17 21:33 UTC, mairaw commented
For sure, I shouldn't be the author for any IIS docs. I also think @John-Hart is probably the best contact here.

2022-08-23 04:17 UTC, wadepickett commented
@John-Hart, is there someone that all Sourabh Shirhatti topics can be assigned to for "ms.author", or at least the ones that are active in some way?

2022-08-23 17:05 UTC, John-Hart commented
@wadepickett you can use John-Hart as the ms.author

2022-08-23 19:02 UTC, wadepickett commented on iis/extensions/database-manager-reference/queryresult-columnmetadata-property-microsoft-web-management-databasemanager.md
> +ms.author: mairaw
```suggestion
ms.author: johnhart
```

2022-08-23 19:03 UTC, wadepickett commented on iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-currentsegmentindexproperty-field-microsoft-web-media-smoothstreaming.md
> +ms.author: mairaw
```suggestion
ms.author: johnhart
```

2022-08-23 19:03 UTC, wadepickett commented on iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-currentsegmentindexproperty-field-microsoft-web-media-smoothstreaming_1.md
> +ms.author: mairaw
```suggestion
ms.author: johnhart
```

2022-08-23 19:03 UTC, wadepickett commented on iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-naturalvideoheightproperty-field-microsoft-web-media-smoothstreaming.md
> +ms.author: mairaw
```suggestion
ms.author: johnhart
```

2022-08-23 19:03 UTC, wadepickett commented on iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-naturalvideowidthproperty-field-microsoft-web-media-smoothstreaming.md
> +ms.author: mairaw
```suggestion
ms.author: johnhart
```

2022-08-23 19:04 UTC, wadepickett commented on iis/extensions/smooth-streaming-client/streamupdatedeventargs-class-microsoft-web-media-smoothstreaming.md
> +ms.author: mairaw
```suggestion
ms.author: johnhart
```

2022-08-23 19:04 UTC, wadepickett commented on iis/extensions/smooth-streaming-client/streamupdatedeventargs-class-microsoft-web-media-smoothstreaming_1.md
> +ms.author: mairaw
```suggestion
ms.author: johnhart
```

2022-08-23 19:04 UTC, wadepickett commented on iis/extensions/smooth-streaming-client/streamupdatedlisteventargs-class-microsoft-web-media-smoothstreaming.md
> +ms.author: mairaw
```suggestion
ms.author: johnhart
```

2022-08-23 19:04 UTC, wadepickett commented on iis/extensions/smooth-streaming-client/streamupdatedlisteventargs-class-microsoft-web-media-smoothstreaming_1.md
> +ms.author: mairaw
```suggestion
ms.author: johnhart
```

2022-08-23 19:07 UTC, wadepickett commented on iis/extensions/database-manager-reference/dependenciesmissingexception-constructor-serializationinfo-streamingcontext-microsoft-web-management-databasemanager.md
> +ms.author: mairaw
```suggestion
ms.author: johnhart
```

2022-08-23 19:08 UTC, wadepickett commented on iis/extensions/database-manager-reference/dependenciesmissingexception-constructor-microsoft-web-management-databasemanager_1.md
> +ms.author: mairaw
```suggestion
ms.author: johnhart
```

2022-08-23 19:10 UTC, wadepickett commented
For ms.author which is internal, it would be johnhart.  for author it would be the github name John-Hart.   Changed those.

2022-08-23 19:12 UTC, wadepickett approved these changes

2022-08-23 19:13 UTC, merged

2022-08-23 20:38 UTC, mairaw commented
Given that the author metadata is set globally, why were they also added to a few individual topics?

2022-08-23 21:39 UTC, wadepickett commented
I don't know the history. I was just jumping in to unstick a few PR that were sitting there a while waiting for help.  Sourabh would know but he is no longer on IIS.

2022-08-23 21:39 UTC, wadepickett commented
I don't know the history. I was just jumping in to unstick a few PR that were sitting there a while waiting for help.  Sourabh would know but he is no longer on IIS.

2022-08-23 21:43 UTC, mairaw commented
@damabe added them on this PR, so there's no history.