Revised the link to fix #526.
MicrosoftDocs/iis-docs pull request #979
Opened 2023-03-12 01:26 UTC by lextm

The IIS 7 SDK Reference page doesn't seem to exist any more. Link to the native code development overview instead.

2023-03-14 20:16 UTC, John-Hart requested changes

2023-03-14 20:16 UTC, John-Hart commented on iis/develop/runtime-extensibility/develop-a-native-cc-module-for-iis.md
> +In this walkthrough, you learned how to develop and deploy a custom native module using the new native (C++) extensibility APIs. Please consult the [IIS 7.0 SDK documentation](../../web-developement-
the original link is working, it's found at https://learn.microsoft.com/en-us/iis/get-started/whats-new-in-iis-10-version-1709/new-features-introduced-in-iis-10-1709

2023-03-15 00:57 UTC, lextm commented on iis/develop/runtime-extensibility/develop-a-native-cc-module-for-iis.md
> +In this walkthrough, you learned how to develop and deploy a custom native module using the new native (C++) extensibility APIs. Please consult the [IIS 7.0 SDK documentation](../../web-developement-
Thanks, John. The what's new page does exist. However, it is not the "IIS 7.0 SDK documentation" required by this link. That's why I changed it to another link instead.

2023-03-15 01:07 UTC, John-Hart commented on iis/develop/runtime-extensibility/develop-a-native-cc-module-for-iis.md
> +In this walkthrough, you learned how to develop and deploy a custom native module using the new native (C++) extensibility APIs. Please consult the [IIS 7.0 SDK documentation](../../web-developement-
How about changing the [IIS 7.0 SDK documentation] to match the document it's pointing to? Maybe something like [Native-Code Development Overview]

2023-03-15 03:21 UTC, lextm commented on iis/develop/runtime-extensibility/develop-a-native-cc-module-for-iis.md
> +In this walkthrough, you learned how to develop and deploy a custom native module using the new native (C++) extensibility APIs. Please consult the [IIS 7.0 SDK documentation](../../web-developement-
Thanks for the advice. Edited as requested.

2023-03-15 16:58 UTC, John-Hart approved these changes

2023-04-25 01:01 UTC, merged